# -*- coding: utf-8 -*-
"""hi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHMXUgYHIKrUKxvLWbCpDiU7ATihKusI
"""

import streamlit as st
st.title("HI")